# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_route_table_association.rtbassoc-074e1ca6299aa53f1:
resource "aws_route_table_association" "rtbassoc-074e1ca6299aa53f1" {
  route_table_id = aws_route_table.rtb-07343146b07e582dc.id
  subnet_id      = aws_subnet.subnet-0f35b82ce3d589085.id
}
