# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_network_interface.eni-01206cca71003a394:
resource "aws_network_interface" "eni-01206cca71003a394" {
  description = "Primary network interface"
  private_ip  = "192.168.4.86"
  private_ips = [
    "192.168.4.86",
  ]
  private_ips_count = 0
  security_groups = [
    aws_security_group.sg-0c991999e3313704a.id,
  ]
  source_dest_check = true
  subnet_id         = aws_subnet.subnet-0aeecc1de70f6997a.id
  tags              = {}

}
