# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_ec2_transit_gateway_route_table.tgw-rtb-05fadccd7b1475c8f:
resource "aws_ec2_transit_gateway_route_table" "tgw-rtb" {
  tags               = {}
  transit_gateway_id = aws_ec2_transit_gateway.mytgw.id
}
