# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_route_table_association.rtbassoc-01b2fe2ddfac5825c:
resource "aws_route_table_association" "myrtbassociation" {
  route_table_id = aws_route_table.rtb2-igw.id
  subnet_id      = aws_subnet.mypubsubnet.id
}
