# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_security_group_rule.sg-0c991999e3313704a-1:
resource "aws_security_group_rule" "mysgingress-80" {
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  from_port         = 80
  ipv6_cidr_blocks  = []
  prefix_list_ids   = []
  protocol          = "tcp"
  security_group_id = aws_security_group.mysg.id
  self              = false
  to_port           = 80
  type              = "ingress"
}
