# File generated by aws2tf see https://github.com/awsandy/aws2tf
# aws_nat_gateway.nat-070132f292c79b9d6:
resource "aws_nat_gateway" "mynatgw" {
  allocation_id = aws_eip.my-eip.id
  subnet_id     = aws_subnet.mypubsubnet.id
  tags          = {}
}
